name: 错误报告
description: 提交错误报告
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间填写此错误报告！
  - type: dropdown
    id: machine
    attributes:
      label: 机器型号
      description: 哪个型号的设备被修补？
      options:
        - MacBook5,1
        - MacBook5,2
        - MacBook6,1
        - MacBook7,1
        - MacBook8,1
        - MacBookAir2,1
        - MacBookAir3,1
        - MacBookAir3,2
        - MacBookAir4,1
        - MacBookAir4,2
        - MacBookAir5,1
        - MacBookAir5,2
        - MacBookAir6,1
        - MacBookAir6,2
        - MacBookPro4,1
        - MacBookPro5,1
        - MacBookPro5,2
        - MacBookPro5,3
        - MacBookPro5,4
        - MacBookPro5,5
        - MacBookPro6,1
        - MacBookPro6,2
        - MacBookPro7,1
        - MacBookPro8,1
        - MacBookPro8,2
        - MacBookPro8,3
        - MacBookPro9,1
        - MacBookPro9,2
        - MacBookPro10,1
        - MacBookPro10,2
        - MacBookPro11,1
        - MacBookPro11,2
        - MacBookPro11,3
        - Macmini3,1
        - Macmini4,1
        - Macmini5,1
        - Macmini5,2
        - Macmini5,3
        - Macmini6,1
        - Macmini6,2
        - iMac7,1
        - iMac8,1
        - iMac9,1
        - iMac10,1
        - iMac11,1
        - iMac11,2
        - iMac11,3
        - iMac12,1
        - iMac12,2
        - iMac13,1
        - iMac13,2
        - iMac13,3
        - iMac14,1
        - iMac14,2
        - iMac14,3
        - iMac14,4
        - iMac15,1
        - MacPro3,1
        - MacPro4,1
        - MacPro5,1
        - Xserve2,1
        - Xserve3,1
        - 其他/不适用
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 应用程序版本
      description: 您运行的是我们软件的哪个构建版本？
      options:
        - 最新构建版 (每夜版)
        - 最新发行版
    validations:
      required: true
  - type: dropdown
    id: variant
    attributes:
      label: 应用程序变体
      description: 您运行的是我们软件的哪个变体？
      options:
        - GUI (图形用户界面)
        - CLI (命令行界面)
        - 其他/不适用
    validations:
      required: true
  - type: dropdown
    id: verify-previously-reported
    attributes:
      label: 您是否已验证此问题之前是否已报告过？如果否，您的问题将被关闭
      description: 如果否，您的问题将被关闭。我们希望用户在提交之前先通过Github Issue搜索进行检查 (https://github.com/pyquick/OCLP-R/issues?q=is%3Aissue)
      multiple: true
      options:
        - '是'
        - '否'
    validations:
      required: true
  - type: dropdown
    id: verify-guide
    attributes:
      label: 您是否已验证我们的指南中是否涵盖了此问题？例如故障排除和旧版加速页面
      description: 如果否，您的问题将被关闭。我们希望用户在提交之前先检查指南 (https://pyquick.github.io/OCLP-R/)
      multiple: true
      options:
        - '是'
        - '否'
    validations:
      required: true
  - type: dropdown
    id: used-forums
    attributes:
      label: 您是否已在我们的Discord服务器上验证过这是修补程序错误而不是macOS错误/用户操作错误？
      description: 如果否，请不要使用问题功能。我们希望用户在提交之前先与他人讨论。问题仅适用于有效的修补程序问题，不适用于个人故障排除会话。
      multiple: true
      options:
        - '是'
        - '否'
    validations:
      required: true
  - type: dropdown
    id: 3rd-party-application
    attributes:
      label: 此问题是否与第三方应用程序有关？
      description: 如果是，请将讨论移至论坛。我们无法投入时间来处理每个可能在macOS中损坏的单个应用程序。仅当您有想要添加到我们项目中的修复方案时才提交问题
      multiple: true
      options:
        - '是'
        - '否'
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: 您在哪些版本的macOS上遇到此问题？
      multiple: true
      options:
        - macOS 12, Monterey
        - macOS 11, Big Sur
        - macOS 10.15, Catalina
        - macOS 10.14, Mojave
        - macOS 10.13, High Sierra
        - macOS 10.12, Sierra
        - macOS 10.11, El Capitan
        - 其他/不适用
    validations:
      required: true
  - type: dropdown
    id: where-issue
    attributes:
      label: 此问题出现在哪里？
      multiple: true
      options:
        - 在启动macOS和登录屏幕之间
        - 在macOS内（登录前）
        - 在macOS内（登录后）
        - 其他/不适用
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 问题是什么？
      description: 此外，请说明您期望发生什么？
      value: "请清楚地解释问题"
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: 您采取了哪些步骤来解决此问题？请包含来自Discord的消息、日志和截图。